#!/usr/bin/env python
import rospy

from mdr_status_led_interface.status_led_interface_base import StatusLedInterfaceBase

if __name__ == '__main__':
    rospy.init_node('mdr_status_led_interface')
    try:
        StatusLedInterfaceBase()
    except rospy.ROSInterruptException:
        pass
